language: node_js
node_js:
- '7'
before_script:
- npm install -g gulp
script: gulp pipeline --environment ci
env:
  global:
  - secure: ebhjQOQF5AepgoRmdUCoIV3OnhgYgGJrarx4qaTdXWY+Kpfz4fRzC2JOZjA0nkRxU2zRyL3NLslNV8j3wbwkjxyPUqGyFgld7xpsNORx3GbHGcLn2ZFOLbJOiVTrQIBArPAFR/giu7ArzlhZnr+O374QaRHIB1yacdLi6gVpH0Xobs2jNpDFp5HfQB72T23kJr/mWQLgmril5dsRILwKY+Cx6I2tBDl5drYQ+MmX4cWusLt0KpwvIvQU+4HcHZVKe1jag3hLQKP7KZLzs6aqp3zCa11EwxHEjoVxKIr2411xxn8xEj6LJREan6cFsClR+lR9pinnXkjxYuv3NAbMCQb/j8F76s1kZYkYMoKGsxtQuh/NMoQ3BWZT0uBu842SKfV2HDP8xTzPEIdwIlsN082lXfgolmLkJ0Bp0KpX6fBZqMQ+ZWPIGLsRUJyhZJrA64tp3VpFvBlVqWGodF+dP3xiPLwjlSZ0YSOyCr+D+FQYdwAG+l/ao7g+lIFxWUw4tAd0qmSQJ8Fnbgnl7NmPzaAdsp9j4ce729kTijhVZO4n9fcVlyrwzm5ExBKxIVGJwp/jRt84CwAyYiAcLw697gDGO3Dfur2wVUrhdq9Ahp7abdTofgk7OrZRe7vVqpYKD4dCQqDxGutUujwLM/Mu26nMbtTe27Z4m6IGmRjX4fA=
  - secure: F7NAcI9FJmDUK17dX8rfI3PveK7+ISrgjjuMNv8ZUGAQa0NYX5X4DLOvPDVdWTWt+tW91edAp5HbcQp6wFpstWjRej4F76W1sJvc6EdKoX3W9OZ/qhKoDhIMPNGiwkvWzmgYNKNWkRxzt+6s4lrqWZxtj8g8DBW9O68Y06bMfFZOGjYKAs5qx7t2mk5VcQc1TxrSCeNyNGPPucR+6TXeVl7sW3LYQScpH7Bu//a1McG9Yrryviduuno1tPn+UkGvQEdT2+FKlIgCe/JLc33yjy9NxSR4M8CvfJTI7RszTMDoo+S21Uoy7PkpXH+ZMhQFXh9a0mnHtUcNagjQw8puoihs2ebWjz5eyy7m/m2dKbbrTpsZA3UtK+UN+f9TV8GcaQzONHgsOz93hGKwkWKIsYn7LLisAw6WToSFSnEBwzyBm4XAcskBJ/XRvMIuvXCJ0udNYRq+hJaQYYiN0xkkOzjOVDtDxQ1PgLwOSssJfCkxdUGK5W6P3PbQ3j5l/X6gI0y67K6zErFNedoAdsCkDxQ5lew8BVw9fanetWcS8Vy8L6rAAmWMYOG1qr02Ma9bPOqGC7/a1y/kMKJkk9LaHkOISiQu0yXKgsEGmgZb0IAvApyCa6nOa9lBxGhWfsx2oP6dpyQhs7FAetbDng0TzHYdKqqOoZdNUJYzHSRHIn4=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8